openapi: 3.0.0
info:
  title: Real-Time Polling API
  version: 1.0.0
  description: API documentation for Real-Time Polling Backend

servers:
  - url: http://localhost:3000

paths:
  /health:
    get:
      summary: Health Check
      responses:
        "200":
          description: Server is running

  /api/users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        "201":
          description: User created

  /api/users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: User details

  /api/polls:
    post:
      summary: Create a new poll
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question: { type: string }
                options: { type: array, items: { type: string } }
                creatorId: { type: integer }
                isPublished: { type: boolean }
      responses:
        "201":
          description: Poll created

  /api/polls/{id}:
    get:
      summary: Get poll with results
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Poll details

  /api/polls/{pollId}/vote:
    post:
      summary: Cast a vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: { type: integer }
                pollOptionId: { type: integer }
      responses:
        "201":
          description: Vote recorded
